from cx_Freeze import setup, Executable

build_exe_options = {
    "include_files": [
        #"GPAC_mac/mp4box"
        # "GPAC_mac/lib/libSDL2-2.0.0.dylib",
        # "GPAC_mac/lib/liba52.0.dylib",
        # "GPAC_mac/lib/libass.9.dylib",
        # "GPAC_mac/lib/libavcodec.58.dylib",
        # "GPAC_mac/lib/libavdevice.58.dylib",
        # "GPAC_mac/lib/libavfilter.7.dylib",
        # "GPAC_mac/lib/libavformat.58.dylib",
        # "GPAC_mac/lib/libavresample.4.dylib",
        # "GPAC_mac/lib/libavutil.56.dylib",
        # "GPAC_mac/lib/libbluray.2.dylib",
        # "GPAC_mac/lib/libcrypto.1.1.dylib",
        # "GPAC_mac/lib/libfaad.2.dylib",
        # "GPAC_mac/lib/libffi.7.dylib",
        # "GPAC_mac/lib/libfontconfig.1.dylib",
        # "GPAC_mac/lib/libfreetype.6.dylib",
        # "GPAC_mac/lib/libfribidi.0.dylib",
        # "GPAC_mac/lib/libgif.dylib",
        # "GPAC_mac/lib/libglib-2.0.0.dylib",
        # "GPAC_mac/lib/libgmp.10.dylib",
        # "GPAC_mac/lib/libgnutls.30.dylib",
        # "GPAC_mac/lib/libgpac.dylib",
        # "GPAC_mac/lib/libgraphite2.3.dylib",
        # "GPAC_mac/lib/libharfbuzz.0.dylib",
        # "GPAC_mac/lib/libhogweed.6.dylib",
        # "GPAC_mac/lib/libidn2.0.dylib",
        # "GPAC_mac/lib/libintl.8.dylib",
        # "GPAC_mac/lib/libjpeg.9.dylib",
        # "GPAC_mac/lib/liblept.5.dylib",
        # "GPAC_mac/lib/liblzma.5.dylib",
        # "GPAC_mac/lib/libmad.0.dylib",
        # "GPAC_mac/lib/libmp3lame.0.dylib",
        # "GPAC_mac/lib/libnettle.8.dylib",
        # "GPAC_mac/lib/libnghttp2.14.dylib",
        # "GPAC_mac/lib/libogg.0.dylib",
        # "GPAC_mac/lib/libopencore-amrnb.0.dylib",
        # "GPAC_mac/lib/libopencore-amrwb.0.dylib",
        # "GPAC_mac/lib/libopenjp2.7.dylib",
        # "GPAC_mac/lib/libopus.0.dylib",
        # "GPAC_mac/lib/libp11-kit.0.dylib",
        # "GPAC_mac/lib/libpcre.1.dylib",
        # "GPAC_mac/lib/libpng16.16.dylib",
        # "GPAC_mac/lib/libpostproc.55.dylib",
        # "GPAC_mac/lib/librtmp.1.dylib",
        # "GPAC_mac/lib/librubberband.2.dylib",
        # "GPAC_mac/lib/libsnappy.1.dylib",
        # "GPAC_mac/lib/libsoxr.0.dylib",
        # "GPAC_mac/lib/libspeex.1.dylib",
        # "GPAC_mac/lib/libssl.1.1.dylib",
        # "GPAC_mac/lib/libswresample.3.dylib",
        # "GPAC_mac/lib/libswscale.5.dylib",
        # "GPAC_mac/lib/libtasn1.6.dylib",
        # "GPAC_mac/lib/libtesseract.4.dylib",
        # "GPAC_mac/lib/libtheora.0.dylib",
        # "GPAC_mac/lib/libtheoradec.1.dylib",
        # "GPAC_mac/lib/libtheoraenc.1.dylib",
        # "GPAC_mac/lib/libtiff.5.dylib",
        # "GPAC_mac/lib/libunistring.2.dylib",
        # "GPAC_mac/lib/libvidstab.1.1.dylib",
        # "GPAC_mac/lib/libvorbis.0.dylib",
        # "GPAC_mac/lib/libvorbisenc.2.dylib",
        # "GPAC_mac/lib/libwebp.7.dylib",
        # "GPAC_mac/lib/libwebpmux.3.dylib",
        # "GPAC_mac/lib/libx264.155.dylib",
        # "GPAC_mac/lib/libx265.179.dylib",
        # "GPAC_mac/modules/gf_openhevc_dec.dylib",
        # "GPAC_mac/modules/gm_ft_font.dylib",
        # "GPAC_mac/modules/gm_sdl_out.dylib",
        # "GPAC_mac/modules/gm_validator.dylib"
    ]
}

bdist_mac_options = {
    
}

setup(
    name="StemGen",
    version="0.1",
    description="StemGen",
    options={"bdist_mac": bdist_mac_options, "build_exe": build_exe_options},
    executables=[Executable("StemGenApp.py", base="gui")],
)